name: Build NightmareVision Engine (Windows)

on:
  push:
    branches: [ main ]
  workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Install dependencies
      run: |
        haxelib setup C:\haxelib
        haxelib install lime
        haxelib install openfl
        haxelib run lime setup
        haxelib run openfl setup
        haxelib install flixel
        haxelib install flixel-addons
        haxelib install flixel-ui
        haxelib install hscript
        haxelib install hxcpp
        haxelib install linc_luajit
        haxelib run lime rebuild linc_luajit windows

    - name: Build the engine
      run: lime build windows -release

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: NightmareVision-Windows-Build
        path: export/release/windows/bin
